METRIC_MAP = {
    "利润总额": ("income_sheet", "total_profit", "万元"),
    "净利润": ("income_sheet", "net_profit", "万元"),
    "主营业务收入": ("income_sheet", "total_operating_revenue", "万元"),
    "营业总收入": ("income_sheet", "total_operating_revenue", "万元"),
    "收入": ("income_sheet", "total_operating_revenue", "万元"),
    "销售额": ("income_sheet", "total_operating_revenue", "万元"),
    "研发费用": ("income_sheet", "operating_expense_rnd_expenses", "万元"),
    "研发投入": ("income_sheet", "operating_expense_rnd_expenses", "万元"),
    "研发情况": ("income_sheet", "operating_expense_rnd_expenses", "万元"),
    "销售费用": ("income_sheet", "operating_expense_selling_expenses", "万元"),
    "管理费用": ("income_sheet", "operating_expense_administrative_expenses", "万元"),
    "财务费用": ("income_sheet", "operating_expense_financial_expenses", "万元"),
    "营业成本": ("income_sheet", "operating_expense_cost_of_sales", "万元"),
    "总资产": ("balance_sheet", "asset_total_assets", "万元"),
    "资产总额": ("balance_sheet", "asset_total_assets", "万元"),
    "总负债": ("balance_sheet", "liability_total_liabilities", "万元"),
    "负债总额": ("balance_sheet", "liability_total_liabilities", "万元"),
    "货币资金": ("balance_sheet", "asset_cash_and_cash_equivalents", "万元"),
    "应收账款": ("balance_sheet", "asset_accounts_receivable", "万元"),
    "存货": ("balance_sheet", "asset_inventory", "万元"),
    "短期借款": ("balance_sheet", "liability_short_term_loans", "万元"),
    "股东权益": ("balance_sheet", "equity_total_equity", "万元"),
    "权益总额": ("balance_sheet", "equity_total_equity", "万元"),
    "资产负债率": ("balance_sheet", "asset_liability_ratio", "%"),
    "收益率": ("core_performance_indicators_sheet", "roe", "%"),
    "净资产收益率": ("core_performance_indicators_sheet", "roe", "%"),
    "加权平均净资产收益率（扣非）": ("core_performance_indicators_sheet", "roe_weighted_excl_non_recurring", "%"),
    "扣非加权平均净资产收益率": ("core_performance_indicators_sheet", "roe_weighted_excl_non_recurring", "%"),
    "扣非ROE": ("core_performance_indicators_sheet", "roe_weighted_excl_non_recurring", "%"),
    "销售毛利率": ("core_performance_indicators_sheet", "gross_profit_margin", "%"),
    "毛利率": ("core_performance_indicators_sheet", "gross_profit_margin", "%"),
    "销售净利率": ("core_performance_indicators_sheet", "net_profit_margin", "%"),
    "净利率": ("core_performance_indicators_sheet", "net_profit_margin", "%"),
    "每股收益": ("core_performance_indicators_sheet", "eps", "元"),
    "净现金流": ("cash_flow_sheet", "net_cash_flow", "元"),
    "经营性现金流量净额": ("cash_flow_sheet", "operating_cf_net_amount", "万元"),
    "经营活动现金流量净额": ("cash_flow_sheet", "operating_cf_net_amount", "万元"),
    "投资性现金流量净额": ("cash_flow_sheet", "investing_cf_net_amount", "万元"),
    "投资现金流量净额": ("cash_flow_sheet", "investing_cf_net_amount", "万元"),
    "筹资性现金流量净额": ("cash_flow_sheet", "financing_cf_net_amount", "万元"),
    "存货周转率": ("__derived__", "inventory_turnover_ratio", "次"),
    "出口业务占比": ("report_export_ratio", "export_ratio_pct", "%"),
}

PERIOD_MAP = {
    "一季度": "Q1",
    "第一季度": "Q1",
    "半年": "HY",
    "半年度": "HY",
    "三季度": "Q3",
    "第三季度": "Q3",
    "前三季度": "Q3",
    "年报": "FY",
    "年度": "FY",
}
